import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Auth from "@/components/Auth";
import { createClient } from "@/utils/supabase-server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  console.log(user);
  return (
    <html className="h-screen w-screen" lang="en">
      <body
        className={`relative ${geistSans.variable} ${geistMono.variable} antialiased bg-gray-200`}
      >
        {user ? (
          <>
            <Nav user={user} />
            {children}
          </>
        ) : (
          <Auth />
        )}
      </body>
    </html>
  );
}
